version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    env_file:
      - .env

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres-cqrs
    hostname: postgres-cqrs
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"

  cassandra:
    image: cassandra:3
    container_name: cassandra
    hostname: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    env_file:
      - .env